export const CHAINS: { slug: string; name: string; iconUrl?: string }[] = [
  { slug: 'eth', name: 'Ethereum', iconUrl: '/assets/eth-logo.svg' },
  { slug: 'bsc', name: 'BNB Smart Chain', iconUrl: '/assets/bnb-logo.svg' },
  { slug: 'polygon', name: 'Polygon' },
  { slug: 'avalanche', name: 'Avalanche' },
  { slug: 'tron', name: 'TRON' },
  { slug: 'bitcoin', name: 'Bitcoin' },
  { slug: 'solana', name: 'Solana' },
  { slug: 'optimism', name: 'Optimism' },
  { slug: 'base', name: 'Base' },
  { slug: 'arbitrum', name: 'Arbitrum One' },
  { slug: 'ton', name: 'TON' },
  { slug: 'dogecoin', name: 'Dogecoin' },
  { slug: 'zcash', name: 'Zcash' },
];
